apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  selector:
    app: mon-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # Port exposé par le service
      targetPort: 80  # Port du container
      nodePort: 30080 # Port accessible depuis Minikube ou cluster
